version: '3.8'
services:
  web:
    build: .
    user: "${UID}:${GID}"
    command: npm run dev
    ports:
      - "3000:3000"
    env_file:
      - .env.local
    environment:
      - NODE_ENV=development
      - PORT=3000
      - NEXT_TELEMETRY_DISABLED=1
    volumes:
      - .:/app:cached
      - /app/node_modules
    restart: always

